/* 
 * OrderCloud
 *
 * A full ecommerce backend as a service.
 *
 * OpenAPI spec version: 0.1
 * Contact: ordercloud@four51.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OrderCloud.Api;
using OrderCloud.Model;
using OrderCloud.Client;
using System.Reflection;

namespace OrderCloud.Test
{
    /// <summary>
    ///  Class for testing EmailTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmailTemplateTests
    {
        // TODO uncomment below to declare an instance variable for EmailTemplate
        //private EmailTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmailTemplate
            //instance = new EmailTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailTemplate
        /// </summary>
        [Test]
        public void EmailTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmailTemplate
            //Assert.IsInstanceOfType<EmailTemplate> (instance, "variable 'instance' is a EmailTemplate");
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'ReplyEmail'
        /// </summary>
        [Test]
        public void ReplyEmailTest()
        {
            // TODO unit test for the property 'ReplyEmail'
        }
        /// <summary>
        /// Test the property 'SendMessageType'
        /// </summary>
        [Test]
        public void SendMessageTypeTest()
        {
            // TODO unit test for the property 'SendMessageType'
        }
        /// <summary>
        /// Test the property 'EmailFormatType'
        /// </summary>
        [Test]
        public void EmailFormatTypeTest()
        {
            // TODO unit test for the property 'EmailFormatType'
        }

    }

}
