/**
 * OrderCloud
 * A full ecommerce backend as a service.
 *
 * OpenAPI spec version: 0.1
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGPaymentTransaction.h
 * 
 * 
 */

#ifndef SWGPaymentTransaction_H_
#define SWGPaymentTransaction_H_

#include <QJsonObject>


#include "SWGNumber.h"
#include "SWGObject.h"
#include <QDate>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGPaymentTransaction: public SWGObject {
public:
    SWGPaymentTransaction();
    SWGPaymentTransaction(QString* json);
    virtual ~SWGPaymentTransaction();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGPaymentTransaction* fromJson(QString &jsonString);

    QString* getID();
    void setID(QString* ID);
QString* getType();
    void setType(QString* Type);
QDate* getDateExecuted();
    void setDateExecuted(QDate* DateExecuted);
SWGNumber* getAmount();
    void setAmount(SWGNumber* Amount);
bool getSucceeded();
    void setSucceeded(bool Succeeded);
QString* getResultCode();
    void setResultCode(QString* ResultCode);
QString* getResultMessage();
    void setResultMessage(QString* ResultMessage);
SWGObject* getXp();
    void setXp(SWGObject* xp);

private:
    QString* ID;
QString* Type;
QDate* DateExecuted;
SWGNumber* Amount;
bool Succeeded;
QString* ResultCode;
QString* ResultMessage;
SWGObject* xp;
};

} /* namespace Swagger */

#endif /* SWGPaymentTransaction_H_ */
