/**
 * OrderCloud
 * A full ecommerce backend as a service.
 *
 * OpenAPI spec version: 0.1
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef _SWG_SWGPaymentApi_H_
#define _SWG_SWGPaymentApi_H_

#include "SWGHttpRequest.h"

#include <QString>
#include "SWGPayment.h"
#include "SWGObject.h"
#include "SWGPaymentTransaction.h"

#include <QObject>

namespace Swagger {

class SWGPaymentApi: public QObject {
    Q_OBJECT

public:
    SWGPaymentApi();
    SWGPaymentApi(QString host, QString basePath);
    ~SWGPaymentApi();

    QString host;
    QString basePath;

    void create(QString* buyerID, QString* orderID, SWGPayment payment);
    void createTransaction(QString* buyerID, QString* orderID, QString* paymentID, SWGPaymentTransaction transaction);
    void delete(QString* buyerID, QString* orderID, QString* paymentID);
    void deleteTransaction(QString* buyerID, QString* orderID, QString* paymentID, QString* transactionID);
    void get(QString* buyerID, QString* orderID, QString* paymentID);
    void list(QString* buyerID, QString* orderID, QString* search, QString* searchOn, QString* sortBy, qint32 page, qint32 pageSize);
    void patch(QString* buyerID, QString* orderID, QString* paymentID, SWGPayment partialPayment);
    void patchTransaction(QString* buyerID, QString* orderID, QString* paymentID, QString* transactionID, SWGPaymentTransaction partialTransaction);
    void update(QString* buyerID, QString* orderID, QString* paymentID, SWGPayment payment);
    void updateTransaction(QString* buyerID, QString* orderID, QString* paymentID, QString* transactionID, SWGPaymentTransaction transaction);
    
private:
    void createCallback (HttpRequestWorker * worker);
    void createTransactionCallback (HttpRequestWorker * worker);
    void deleteCallback (HttpRequestWorker * worker);
    void deleteTransactionCallback (HttpRequestWorker * worker);
    void getCallback (HttpRequestWorker * worker);
    void listCallback (HttpRequestWorker * worker);
    void patchCallback (HttpRequestWorker * worker);
    void patchTransactionCallback (HttpRequestWorker * worker);
    void updateCallback (HttpRequestWorker * worker);
    void updateTransactionCallback (HttpRequestWorker * worker);
    
signals:
    void createSignal(SWGObject* summary);
    void createTransactionSignal(SWGObject* summary);
    void deleteSignal();
    void deleteTransactionSignal();
    void getSignal(SWGObject* summary);
    void listSignal(SWGObject* summary);
    void patchSignal(SWGObject* summary);
    void patchTransactionSignal(SWGObject* summary);
    void updateSignal(SWGObject* summary);
    void updateTransactionSignal(SWGObject* summary);
    
};
}
#endif
