/**
 * OrderCloud
 * A full ecommerce backend as a service.
 *
 * OpenAPI spec version: 0.1
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGPaymentTransaction.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGPaymentTransaction::SWGPaymentTransaction(QString* json) {
    init();
    this->fromJson(*json);
}

SWGPaymentTransaction::SWGPaymentTransaction() {
    init();
}

SWGPaymentTransaction::~SWGPaymentTransaction() {
    this->cleanup();
}

void
SWGPaymentTransaction::init() {
    ID = new QString("");
Type = new QString("");
DateExecuted = NULL;
Amount = 0.0;
Succeeded = false;
ResultCode = new QString("");
ResultMessage = new QString("");
xp = NULL;
}

void
SWGPaymentTransaction::cleanup() {
    if(ID != NULL) {
        delete ID;
    }
if(Type != NULL) {
        delete Type;
    }
if(DateExecuted != NULL) {
        delete DateExecuted;
    }
if(Amount != NULL) {
        delete Amount;
    }

if(ResultCode != NULL) {
        delete ResultCode;
    }
if(ResultMessage != NULL) {
        delete ResultMessage;
    }
if(xp != NULL) {
        delete xp;
    }
}

SWGPaymentTransaction*
SWGPaymentTransaction::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGPaymentTransaction::fromJsonObject(QJsonObject &pJson) {
    setValue(&ID, pJson["ID"], "QString", "QString");
setValue(&Type, pJson["Type"], "QString", "QString");
setValue(&DateExecuted, pJson["DateExecuted"], "QDate", "QDate");
setValue(&Amount, pJson["Amount"], "SWGNumber", "SWGNumber");
setValue(&Succeeded, pJson["Succeeded"], "bool", "");
setValue(&ResultCode, pJson["ResultCode"], "QString", "QString");
setValue(&ResultMessage, pJson["ResultMessage"], "QString", "QString");
setValue(&xp, pJson["xp"], "SWGObject", "SWGObject");
}

QString
SWGPaymentTransaction::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGPaymentTransaction::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("ID"), ID, obj, QString("QString"));
    
        

    
    toJsonValue(QString("Type"), Type, obj, QString("QString"));
    
        

    
    toJsonValue(QString("DateExecuted"), DateExecuted, obj, QString("QDate"));
    
        

    
    toJsonValue(QString("Amount"), Amount, obj, QString("SWGNumber"));
    
        
obj->insert("Succeeded", QJsonValue(Succeeded));

    
    toJsonValue(QString("ResultCode"), ResultCode, obj, QString("QString"));
    
        

    
    toJsonValue(QString("ResultMessage"), ResultMessage, obj, QString("QString"));
    
        

    
    toJsonValue(QString("xp"), xp, obj, QString("SWGObject"));
    
        

    return obj;
}

QString*
SWGPaymentTransaction::getID() {
    return ID;
}
void
SWGPaymentTransaction::setID(QString* ID) {
    this->ID = ID;
}

QString*
SWGPaymentTransaction::getType() {
    return Type;
}
void
SWGPaymentTransaction::setType(QString* Type) {
    this->Type = Type;
}

QDate*
SWGPaymentTransaction::getDateExecuted() {
    return DateExecuted;
}
void
SWGPaymentTransaction::setDateExecuted(QDate* DateExecuted) {
    this->DateExecuted = DateExecuted;
}

SWGNumber*
SWGPaymentTransaction::getAmount() {
    return Amount;
}
void
SWGPaymentTransaction::setAmount(SWGNumber* Amount) {
    this->Amount = Amount;
}

bool
SWGPaymentTransaction::getSucceeded() {
    return Succeeded;
}
void
SWGPaymentTransaction::setSucceeded(bool Succeeded) {
    this->Succeeded = Succeeded;
}

QString*
SWGPaymentTransaction::getResultCode() {
    return ResultCode;
}
void
SWGPaymentTransaction::setResultCode(QString* ResultCode) {
    this->ResultCode = ResultCode;
}

QString*
SWGPaymentTransaction::getResultMessage() {
    return ResultMessage;
}
void
SWGPaymentTransaction::setResultMessage(QString* ResultMessage) {
    this->ResultMessage = ResultMessage;
}

SWGObject*
SWGPaymentTransaction::getXp() {
    return xp;
}
void
SWGPaymentTransaction::setXp(SWGObject* xp) {
    this->xp = xp;
}



} /* namespace Swagger */

