/**
 * OrderCloud
 * A full ecommerce backend as a service.
 *
 * OpenAPI spec version: 0.1
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * PasswordReset.h
 * 
 * 
 */

#ifndef PasswordReset_H_
#define PasswordReset_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  PasswordReset
	: public ModelBase
{
public:
    PasswordReset();
    virtual ~PasswordReset();

	/////////////////////////////////////////////
	/// ModelBase overrides
	
    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;
    
 	/////////////////////////////////////////////
	/// PasswordReset members
	   
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getClientID() const;
    void setClientID(utility::string_t value);
    bool ClientIDIsSet() const;
    void unsetClientID();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUsername() const;
    void setUsername(utility::string_t value);
    bool UsernameIsSet() const;
    void unsetUsername();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPassword() const;
    void setPassword(utility::string_t value);
    bool PasswordIsSet() const;
    void unsetPassword();
    
protected:
    utility::string_t m_ClientID;
    bool m_ClientIDIsSet;
utility::string_t m_Username;
    bool m_UsernameIsSet;
utility::string_t m_Password;
    bool m_PasswordIsSet;
};

}
}
}
}

#endif /* PasswordReset_H_ */
