//
// PromotionAssignment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PromotionAssignment: JSONEncodable {
    public var promotionID: String?
    public var buyerID: String?
    public var userID: String?
    public var userGroupID: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["PromotionID"] = self.promotionID
        nillableDictionary["BuyerID"] = self.buyerID
        nillableDictionary["UserID"] = self.userID
        nillableDictionary["UserGroupID"] = self.userGroupID
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
