<?php

/**
 * OrderCloud
 * A full ecommerce backend as a service.
 *
 * OpenAPI spec version: 0.1
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PriceScheduleApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation create
     *
     * .
     *
     *
     * @return Http response
     */
    public function create()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['priceSchedule'])) {
            throw new \InvalidArgumentException('Missing the required parameter $priceSchedule when calling create');
        }
        $priceSchedule = $input['priceSchedule'];


        return response('How about implementing create as a POST method ?');
    }
    /**
     * Operation list
     *
     * .
     *
     *
     * @return Http response
     */
    public function list()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $search = $input['search'];

        $searchOn = $input['searchOn'];

        $sortBy = $input['sortBy'];

        $page = $input['page'];

        $pageSize = $input['pageSize'];


        return response('How about implementing list as a GET method ?');
    }
    /**
     * Operation delete
     *
     * .
     *
     * @param String $priceScheduleID ID of the price schedule. (required)
     *
     * @return Http response
     */
    public function delete($priceScheduleID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing delete as a DELETE method ?');
    }
    /**
     * Operation get
     *
     * .
     *
     * @param String $priceScheduleID ID of the price schedule. (required)
     *
     * @return Http response
     */
    public function get($priceScheduleID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing get as a GET method ?');
    }
    /**
     * Operation patch
     *
     * .
     *
     * @param String $priceScheduleID ID of the price schedule. (required)
     *
     * @return Http response
     */
    public function patch($priceScheduleID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing patch as a PATCH method ?');
    }
    /**
     * Operation update
     *
     * .
     *
     * @param String $priceScheduleID ID of the price schedule. (required)
     *
     * @return Http response
     */
    public function update($priceScheduleID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing update as a PUT method ?');
    }
    /**
     * Operation deletePriceBreak
     *
     * .
     *
     * @param String $priceScheduleID ID of the price schedule. (required)
     *
     * @return Http response
     */
    public function deletePriceBreak($priceScheduleID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deletePriceBreak as a DELETE method ?');
    }
    /**
     * Operation savePriceBreak
     *
     * .
     *
     * @param String $priceScheduleID ID of the price schedule. (required)
     *
     * @return Http response
     */
    public function savePriceBreak($priceScheduleID)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing savePriceBreak as a POST method ?');
    }
}
